//! GPUI's authoring layer.
//!
//! This crate will hold the element, window and application layer that authors
//! write against — the input and gesture vocabulary first, with the reactive
//! store and the window that drives them to follow. It sits above the leaf
//! crates (`gpui_types`, `gpui_engine`, `gpui_platform`) and below the `gpui`
//! facade, which re-exports it so `gpui::ClickEvent` and friends are unchanged.
//!
//! The element-side half of input lives here; the platform-side half — the
//! payload types and `PlatformInput` itself — stays in [`gpui_platform`], which
//! a backend can implement without depending on the whole framework.

#![warn(missing_docs)]

// Macros generated by `gpui_macros` name `gpui::` paths, so within this crate
// `gpui` is an alias for `gpui_authoring`.
extern crate self as gpui;

pub mod gestures;
pub mod interactive;

mod seal {
    /// A mechanism for restricting implementations of a trait to only those in GPUI.
    /// See: <https://predr.ag/blog/definitive-guide-to-sealed-traits-in-rust/>
    pub trait Sealed {}
}

pub use gestures::*;
pub use interactive::*;

pub use gpui_platform::*;
