//! GPUI's authoring layer: the reactive store, the windows, and the declarative
//! element DSL that composes them.
//!
//! This crate holds [`App`], [`Window`] and the context types, the entities and views
//! built on them, and the element tree that renders through the engine contracts in
//! [`gpui_engine`] onto the windowing SPI in [`gpui_platform`].
//!
//! The element DSL is not separable from the runtime: an element is laid out and painted
//! with a concrete [`Window`] and [`App`], so everything an author writes against lives
//! here. What is swappable sits underneath — the scene and atlas vocabulary, the
//! platform SPI, and the font, line-layout and line-wrap traits — or rides along in [`Style`]. The element-side half of input lives here too; the platform-side
//! half — the payload types and `PlatformInput` itself — stays in [`gpui_platform`],
//! which a backend can implement without depending on the whole framework.
//!
//! Above this crate sits `gpui`: a thin facade re-exporting this crate and the leaves,
//! so applications keep importing `gpui`.

#![warn(missing_docs)]
#![allow(clippy::type_complexity)] // Not useful, GPUI makes heavy use of callbacks
#![allow(clippy::collapsible_else_if)] // False positives in platform specific code
#![allow(unused_mut)] // False positives in platform specific code

// Macros generated by `gpui_macros` name `gpui::` paths, so within this crate
// `gpui` is an alias for `gpui_authoring`.
extern crate self as gpui;

// Every module below is public so that the `gpui` facade can re-export it from a shim at
// the module's old path, keeping `gpui::colors::…`-style paths alive; its contents are
// re-exported flat at this crate's root as well.
#[macro_use]
/// Actions and the `actions!`/`register_action!` macros that define them.
pub mod action;
/// Sampled animated values and the motion that drives them.
pub mod animated;
/// The application store: [`App`], the entity map, globals and the context types.
pub mod app;

mod arena;
/// Asynchronous asset loading, caching and invalidation.
pub mod asset_cache;
/// Asset source resolution for images and fonts.
pub mod assets;
/// The default colors used by GPUI.
pub mod colors;
/// The frame-time debug overlay.
#[cfg(feature = "profiler")]
pub mod debug_overlay;
/// The `Element`/`IntoElement`/`Render` vocabulary and the element id machinery.
pub mod element;
/// The element implementations: `div`, text, images, lists and the rest.
pub mod elements;
/// The `TaskExt` extension trait over the leaf's `Task`; the executors themselves live in
/// `gpui_platform`.
pub mod executor;
/// Touch gesture recognition vocabulary.
pub mod gestures;
/// The `Global` trait and the helpers for app-wide state.
pub mod global;
/// Text input: the `EntityInputHandler` trait and the input-handler plumbing.
pub mod input;
/// The element inspector.
pub mod inspector;
/// The element-side input vocabulary and its platform conversions.
pub mod interactive;
mod key_dispatch;
/// Key bindings, key contexts and the binding matcher.
pub mod keymap;
/// The `Lerp` trait for interpolating between values.
pub mod lerp;
/// Durations, easing and normalized animation progress.
pub mod motion;
/// The `PathBuilder` for constructing vector paths.
pub mod path_builder;
/// The platform SPI, the window options and the platform-side value types.
pub mod platform;
/// The prelude: the names an application usually wants in scope.
pub mod prelude;
/// Profiling utilities for task, frame, and thread performance tracking.
pub mod profiler;
#[cfg(any(
    test,
    target_os = "windows",
    target_os = "linux",
    target_family = "wasm",
    feature = "test-support",
    feature = "bench-support"
))]
pub use gpui_platform::queue;
/// A cheaply cloneable URI shared across renders.
pub mod shared_uri;
/// Spring animations and their configuration.
pub mod spring;
/// `Style` and the style-refinement DSL.
pub mod style;
/// Animated transitions between style values.
pub mod style_transitions;
/// The `Styled`/`Styleable` extension traits applied to elements.
pub mod styled;
/// RAII subscriptions to entity, global and window events.
pub mod subscription;
/// The `SvgRenderer` trait and SVG loading.
pub mod svg_renderer;
mod tab_stop;
mod taffy;
/// Test-only harnesses: `TestAppContext`, `TestWindow` and the test platform.
#[cfg(any(test, feature = "test-support"))]
pub mod test;
/// The text system, line layout and line wrapping.
pub mod text_system;
/// Animated transitions between arbitrary values.
pub mod transition;
mod util;
/// `AnyView` and the view-level helpers.
pub mod view;
/// The per-window state: rendering, input, focus and the element tree.
pub mod window;

#[cfg(any(test, feature = "test-support"))]
pub use proptest;

#[cfg(doc)]
pub mod _accessibility;
#[cfg(doc)]
pub mod _ownership_and_data_flow;

/// Do not touch, here be dragons for use by gpui_macros and such.
#[doc(hidden)]
pub mod private {
    pub use anyhow;
    pub use inventory;
    pub use schemars;
    pub use serde;
    pub use serde_json;
}

mod seal {
    /// A mechanism for restricting implementations of a trait to only those in GPUI.
    /// See: <https://predr.ag/blog/definitive-guide-to-sealed-traits-in-rust/>
    pub trait Sealed {}
}

pub use accesskit;
pub use accesskit::Action as AccessibleAction;
pub use accesskit::{Orientation, Role, Toggled};
pub use action::*;
pub use animated::*;
pub use anyhow::Result;
pub use app::*;
pub(crate) use arena::*;
pub use asset_cache::*;
pub use assets::*;
pub use ctor::ctor;
#[cfg(feature = "profiler")]
pub use debug_overlay::*;
pub use element::*;
pub use elements::*;
pub use executor::*;
pub use gestures::*;
pub use global::*;
pub use gpui_macros::{
    AppContext, IntoElement, Render, VisualContext, bench, property_test, register_action, test,
};
pub use spring::*;
pub use gpui_ce_types::*;
pub use gpui_shared_string::*;
pub use gpui_types::*;

// `gpui_types` and `gpui_ce_types` both name `Shadow`: upstream's inset flag is a
// `u32`, this fork's is a `ShaderBool`. An explicit re-export shadows the globs,
// so the fork's own type is what this layer publishes.
pub use gpui_ce_types::Shadow;
pub use gpui_util::arc_cow::ArcCow;
/// HTTP client abstraction for making requests.
pub mod http_client;
pub use input::*;
pub use inspector::*;
pub use interactive::*;
use key_dispatch::*;
pub use keymap::*;
pub use lerp::*;
pub use motion::*;
pub use path_builder::*;
pub use platform::*;
pub use profiler::*;
#[cfg(any(target_os = "windows", target_os = "linux", target_family = "wasm"))]
pub use queue::{PriorityQueueReceiver, PriorityQueueSender};
pub use refineable::*;
pub use shared_uri::*;
use std::{any::Any, future::Future};
pub use style::*;
pub use style_transitions::*;
pub use styled::*;
pub use subscription::*;
pub use svg_renderer::*;
pub(crate) use tab_stop::*;
pub use taffy::LayoutId;
use taffy::TaffyLayoutEngine;
#[cfg(any(test, feature = "test-support"))]
pub use test::*;
pub use text_system::*;
// Deliberately the last of the globs: the modules above re-export names it also carries, and a
// glob placed before them makes their re-exports look unused.
pub use gpui_engine::*;
// Placed after `gpui_engine` for the same reason: `gpui_platform` also re-exports the
// `gpui_types`/`gpui_shared_string` names the modules above carry.
pub use gpui_platform::*;
pub use transition::*;
pub use util::{FutureExt, Timeout};
pub use view::*;
pub use window::*;

#[cfg(not(target_family = "wasm"))]
pub use pollster::block_on;

/// Extension methods on [`Bounds`] that need to resolve the application's displays.
///
/// These live in the authoring layer rather than `gpui_types` because they require
/// [`App`], while the base [`Bounds`] type is defined in the platform-agnostic
/// `gpui_types` crate.
pub trait BoundsExt: Sized {
    /// Generate a centered bounds for the given display or primary display if none is provided
    fn centered(display_id: Option<DisplayId>, size: Size<Pixels>, cx: &App) -> Self;

    /// Generate maximized bounds for the given display or primary display if none is provided
    fn maximized(display_id: Option<DisplayId>, cx: &App) -> Self;
}

impl BoundsExt for Bounds<Pixels> {
    fn centered(display_id: Option<DisplayId>, size: Size<Pixels>, cx: &App) -> Self {
        let display = display_id
            .and_then(|id| cx.find_display(id))
            .or_else(|| cx.primary_display());

        display
            .map(|display| Bounds::centered_at(display.bounds().center(), size))
            .unwrap_or_else(|| Bounds {
                origin: point(px(0.), px(0.)),
                size,
            })
    }

    fn maximized(display_id: Option<DisplayId>, cx: &App) -> Self {
        let display = display_id
            .and_then(|id| cx.find_display(id))
            .or_else(|| cx.primary_display());

        display
            .map(|display| display.bounds())
            .unwrap_or_else(|| Bounds {
                origin: point(px(0.), px(0.)),
                size: size(px(1024.), px(768.)),
            })
    }
}

impl HasRemSize for Window {
    fn rem_size(&self) -> Pixels {
        Window::rem_size(self)
    }
}

/// The context trait, allows the different contexts in GPUI to be used
/// interchangeably for certain operations.
pub trait AppContext {
    /// Create a new entity in the app context.
    #[expect(
        clippy::wrong_self_convention,
        reason = "`App::new` is an ubiquitous function for creating entities"
    )]
    fn new<T: 'static>(&mut self, build_entity: impl FnOnce(&mut Context<T>) -> T) -> Entity<T>;

    /// Reserve a slot for a entity to be inserted later.
    /// The returned [Reservation] allows you to obtain the [EntityId] for the future entity.
    fn reserve_entity<T: 'static>(&mut self) -> Reservation<T>;

    /// Insert a new entity in the app context based on a [Reservation] previously obtained from [`reserve_entity`].
    ///
    /// [`reserve_entity`]: Self::reserve_entity
    fn insert_entity<T: 'static>(
        &mut self,
        reservation: Reservation<T>,
        build_entity: impl FnOnce(&mut Context<T>) -> T,
    ) -> Entity<T>;

    /// Update a entity in the app context.
    fn update_entity<T, R>(
        &mut self,
        handle: &Entity<T>,
        update: impl FnOnce(&mut T, &mut Context<T>) -> R,
    ) -> R
    where
        T: 'static;

    /// Update a entity in the app context.
    fn as_mut<'a, T>(&'a mut self, handle: &Entity<T>) -> GpuiBorrow<'a, T>
    where
        T: 'static;

    /// Read a entity from the app context.
    fn read_entity<T, R>(&self, handle: &Entity<T>, read: impl FnOnce(&T, &App) -> R) -> R
    where
        T: 'static;

    /// Tell GPUI that an entity has changed and observers of it should be notified.
    fn notify(&mut self, entity_id: EntityId);

    /// Emit an event of the specified type, which can be handled by other entities that have subscribed via `subscribe` methods on their respective contexts.
    /// A globally-callable equivalent to `Context::emit` without requiring an entity update.
    fn emit<EntityType, EventType>(&mut self, entity: &Entity<EntityType>, event: EventType)
    where
        EntityType: EventEmitter<EventType>,
        EventType: 'static;

    /// Update a window for the given handle.
    fn update_window<T, F>(&mut self, window: AnyWindowHandle, f: F) -> Result<T>
    where
        F: FnOnce(AnyView, &mut Window, &mut App) -> T;

    /// Run `f` against the entity's *current* window — the most recently
    /// rendered window that referenced the entity. Returns `None` if the
    /// entity has no current window or that window is unavailable. See
    /// [`App::with_window`] for the underlying lookup.
    fn with_window<R>(
        &mut self,
        entity_id: EntityId,
        f: impl FnOnce(&mut Window, &mut App) -> R,
    ) -> Option<R>;

    /// Read a window off of the application context.
    fn read_window<T, R>(
        &self,
        window: &WindowHandle<T>,
        read: impl FnOnce(Entity<T>, &App) -> R,
    ) -> Result<R>
    where
        T: 'static;

    /// Spawn a future on a background thread
    fn background_spawn<R>(&self, future: impl Future<Output = R> + Send + 'static) -> Task<R>
    where
        R: Send + 'static;

    /// Read a global from this app context
    fn read_global<G, R>(&self, callback: impl FnOnce(&G, &App) -> R) -> R
    where
        G: Global;

    /// Stores an entity in the app such that it wont be dropped if no other entities are referencing it.
    /// Entities stored this way are dropped when the app is dropped, unless otherwise removed by [`Self::remove_global_entity`].
    fn insert_global_entity<T: 'static>(&mut self, entity: Entity<T>);

    /// Removes the entity from global storage. If no other entities are holding reference to it,
    /// it will be dropped in the very near future.
    fn remove_global_entity<T: 'static>(&mut self, entity: &Entity<T>);

    /// Returns an iterator of all globally-stored entities which match the provided type.
    fn global_entities<T: 'static>(&self) -> impl Iterator<Item = Entity<T>>;
}

/// Returned by [Context::reserve_entity] to later be passed to [Context::insert_entity].
/// Allows you to obtain the [EntityId] for a entity before it is created.
pub struct Reservation<T>(pub(crate) Slot<T>);

impl<T: 'static> Reservation<T> {
    /// Returns the [EntityId] that will be associated with the entity once it is inserted.
    pub fn entity_id(&self) -> EntityId {
        self.0.entity_id()
    }
}

/// This trait is used for the different visual contexts in GPUI that
/// require a window to be present.
pub trait VisualContext: AppContext {
    /// The result type for window operations.
    type Result<T>;

    /// Returns the handle of the window associated with this context.
    fn window_handle(&self) -> AnyWindowHandle;

    /// Update a view with the given callback
    fn update_window_entity<T: 'static, R>(
        &mut self,
        entity: &Entity<T>,
        update: impl FnOnce(&mut T, &mut Window, &mut Context<T>) -> R,
    ) -> Self::Result<R>;

    /// Create a new entity, with access to `Window`.
    fn new_window_entity<T: 'static>(
        &mut self,
        build_entity: impl FnOnce(&mut Window, &mut Context<T>) -> T,
    ) -> Self::Result<Entity<T>>;

    /// Replace the root view of a window with a new view.
    fn replace_root_view<V>(
        &mut self,
        build_view: impl FnOnce(&mut Window, &mut Context<V>) -> V,
    ) -> Self::Result<Entity<V>>
    where
        V: 'static + Render;

    /// Focus a entity in the window, if it implements the [`Focusable`] trait.
    fn focus<V>(&mut self, entity: &Entity<V>) -> Self::Result<()>
    where
        V: Focusable;
}

/// A trait for tying together the types of a GPUI entity and the events it can
/// emit.
pub trait EventEmitter<E: Any>: 'static {}

/// A helper trait for auto-implementing certain methods on contexts that
/// can be used interchangeably.
pub trait BorrowAppContext {
    /// Set a global value on the context.
    fn set_global<T: Global>(&mut self, global: T);
    /// Updates the global state of the given type.
    fn update_global<G, R>(&mut self, f: impl FnOnce(&mut G, &mut Self) -> R) -> R
    where
        G: Global;
    /// Updates the global state of the given type, creating a default if it didn't exist before.
    fn update_default_global<G, R>(&mut self, f: impl FnOnce(&mut G, &mut Self) -> R) -> R
    where
        G: Global + Default;
}

impl<C> BorrowAppContext for C
where
    C: std::borrow::BorrowMut<App>,
{
    fn set_global<G: Global>(&mut self, global: G) {
        self.borrow_mut().set_global(global)
    }

    #[track_caller]
    fn update_global<G, R>(&mut self, f: impl FnOnce(&mut G, &mut Self) -> R) -> R
    where
        G: Global,
    {
        let mut global = self.borrow_mut().lease_global::<G>();
        let result = f(&mut global, self);
        self.borrow_mut().end_global_lease(global);
        result
    }

    fn update_default_global<G, R>(&mut self, f: impl FnOnce(&mut G, &mut Self) -> R) -> R
    where
        G: Global + Default,
    {
        self.borrow_mut().default_global::<G>();
        self.update_global(f)
    }
}

/// Information about the GPU GPUI is running on.
#[derive(Default, Debug, serde::Serialize, serde::Deserialize, Clone)]
pub struct GpuSpecs {
    /// Whether the GPU is really a fake (like `llvmpipe`) running on the CPU.
    pub is_software_emulated: bool,
    /// The name of the device, as reported by Vulkan.
    pub device_name: String,
    /// The name of the driver, as reported by Vulkan.
    pub driver_name: String,
    /// Further information about the driver, as reported by Vulkan.
    pub driver_info: String,
}
